extends: "eslint:recommended"

env:
  browser: true
  es6: true
  jasmine: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType: "module"

rules:
  arrow-parens: [2, "as-needed"]
  arrow-spacing: [2, {before: true, after: true}]
  block-spacing: 2
  brace-style: [2, "stroustrup", {allowSingleLine: true}]
  camelcase: [2, {properties: "always"}]
  comma-dangle: 2
  comma-spacing: 2
  comma-style: [2, "last"]
  complexity: [0, 10]
  computed-property-spacing: [2, "never"]
  curly: [2, "multi-line"]
  default-case: 2
  dot-location: [2, "property"]
  dot-notation: [2, {allowKeywords: true}]
  eol-last: 2
  eqeqeq: 2
  func-style: [2, "declaration", {allowArrowFunctions: true }]
  generator-star-spacing: [2, {before: false, after: true}]
  indent: [2, 2, {SwitchCase: 1, VariableDeclarator: 2}]
  key-spacing: [2, {beforeColon: false, afterColon: true}]
  keyword-spacing: 2
  new-cap: 2
  new-parens: 2
  no-alert: 2
  no-caller: 2
  no-duplicate-imports: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-floating-decimal: 2
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-mixed-operators: 2
  no-mixed-requires: 2
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-nested-ternary: 2
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-octal-escape: 2
  no-path-concat: 2
  no-process-exit: 2
  no-proto: 2
  no-script-url: 2
  no-sequences: 2
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-tabs: 2
  no-trailing-spaces: 2
  no-undef-init: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {vars: "all", args: "after-used"}]
  no-useless-concat: 2
  no-useless-rename: 2
  no-whitespace-before-property: 2
  no-with: 2
  quotes: [2, "single"]
  rest-spread-spacing: [2, "never"]
  semi: 2
  semi-spacing: [2, {before: false, after: true}]
  space-before-blocks: 2
  space-before-function-paren: [2, "never"]
  space-infix-ops: 2
  space-unary-ops: [2, {words: true, nonwords: false}]
  spaced-comment: [2, "always", {exceptions: ["-", "="]}]
  valid-jsdoc: [2, {prefer: {return: "returns"}}]
  wrap-iife: 2
  yoda: [2, "never"]
